# CONFIGURAÇÃO DO BANCO DE DADOS MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_estoque?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=Abdiel
spring.datasource.password=Neguinho2010@

# CONFIGURAÇÕES DO JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ddl-auto=update: O Hibernate vai criar a tabela "produtos" sozinho dentro do MySQL
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL de INSERT no console para você acompanhar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true